APP_SOFTWARE_MODEL_REV = "605001C4"

DATA_DIR_NAME = "Data_Files"
STARTUP_JSON_NAME = "startup.json"
UI_SCREEN1_FILE = "RC_page1b.ui"
UI_SCREEN2_FILE = "RC_Setup_Page_2.ui"

DEFAULT_TREE_FILE_NAME = "Test"

COLOR_ACTIVE = "pale green"
COLOR_INACTIVE = "grey94"
COLOR_DEFAULT = "white"

SERIAL_BAUDRATE = 115200
SERIAL_WINDOWS_PORT = "COM8"
SERIAL_LINUX_PORT = "/dev/ttyUSB0"
SERIAL_INIT_SLEEP_SEC = 0.2
SERIAL_DEINIT_SLEEP_SEC = 0.3
SERIAL_TICK_SLEEP_SEC = 0.25
POS_STALE_SEC = 2.0
DIA_STALE_SEC = 2.0

MODE_LOAD = 0
MODE_AUTO = 1
MODE_MANUAL = 2
